apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipv6-pool
  namespace: metallb-system
spec:
  addresses:
    - fd12:3456:789a:1::240/128
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ipv6-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - ipv6-pool
