version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      microsoft:
        patterns: ["Microsoft.*", "System.*"]
      opentelemetry:
        patterns: ["OpenTelemetry*"]

  - package-ecosystem: npm
    directory: /src/Web
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /src/Api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /src/Diagnostics
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /src/Web
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
