{{- if .Values.quota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "lg.fullname" . }}
  labels:
    {{- include "lg.baseLabels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.quota.hard | nindent 4 }}
{{- end }}
{{- if .Values.limitRange.enabled }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "lg.fullname" . }}
  labels:
    {{- include "lg.baseLabels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        {{- toYaml .Values.limitRange.default | nindent 8 }}
      defaultRequest:
        {{- toYaml .Values.limitRange.defaultRequest | nindent 8 }}
      max:
        {{- toYaml .Values.limitRange.max | nindent 8 }}
{{- end }}
