{{- range $c := list "web" "api" "diagnostics" }}
{{- $ctx := dict "root" $ "component" $c }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lg.componentName" $ctx }}
  labels:
    {{- include "lg.labels" $ctx | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
