apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-monitoring
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  nfs:
    server: 192.0.2.10
    path: /srv/nfs/share/prometheus
